version: "3.8"

services:
    database:
        image: mysql:8
        container_name: um_mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: onixy
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: um_phpmyadmin
        restart: always
        ports:
            - "9001:80"
        environment:
            - PMA_ARBITRARY=1
        depends_on:
            - database

    backend:
        build: .
        container_name: backend_app
        restart: always
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - database
        ports:
            - "9000:9000"

volumes:
    db_data:
